pipeline {
    agent any
    
    environment {

        JIRA_URL = 'https://your-domain.atlassian.net' 
        
        // Your Jira Project Key (e.g., KAN, SCRUM)
        PROJECT_KEY = 'SCRUM' 
        
        // Loads username/token from Jenkins Credentials Vault
        JIRA_CREDS = credentials('jira-creds') 
    }

    stages {
        stage('Sanity Check') {
            steps {
                script {
                    echo "Verifying Docker Connectivity..."
                    sh 'docker ps'
                }
            }
        }

        stage('Build & Test') {
            steps {
                echo "Simulating Application Build..."
                sh 'sleep 2' 
                echo "Build Successful."
            }
        }

        stage('Jira Reporting') {
            steps {
                script {
                    echo "Checking system health and updating Jira..."
                    // This block creates the ticket using the Jira API
                    sh '''
                        # 1. Prepare Ticket Data
                        cat <<EOF > issue.json
                        {
                            "fields": {
                               "project": {"key": "'"$PROJECT_KEY"'"},
                               "summary": "Automated Build Report #${BUILD_NUMBER}",
                               "description": "This is an automated report generated by the Jenkins CI/CD Pipeline.\\nBuild Status: Success\\nTimestamp: $(date)",
                               "issuetype": {"name": "Task"}
                            }
                        }
EOF
                        
                        # 2. Send to Jira
                        # Note: We use the credentials variable injected by Jenkins
                        curl -D- -u $JIRA_CREDS_USR:$JIRA_CREDS_PSW \
                            -X POST \
                            -H "Content-Type: application/json" \
                            --data @issue.json \
                            "$JIRA_URL/rest/api/2/issue"
                    '''
                }
            }
        }
    }
}
